# Generated by Django 3.2.4 on 2022-01-21 10:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(blank=True, max_length=1000, verbose_name='Ключевые слова')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('delivery', models.CharField(blank=True, max_length=255, verbose_name='Доставка и оплата')),
                ('name', models.CharField(max_length=500, verbose_name='Название раздела')),
                ('payment', models.CharField(max_length=500, verbose_name='Оплата')),
                ('top_text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Вступительный текст')),
                ('bottom_text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Нижний текст')),
                ('paypal_logo', models.BooleanField(default=True, verbose_name='логотип PayPal')),
                ('visa_logo', models.BooleanField(default=True, verbose_name='логотип Visa')),
                ('master_logo', models.BooleanField(default=True, verbose_name='логотип Master Card')),
                ('mir_logo', models.BooleanField(default=True, verbose_name='логотип МИР')),
                ('terminal_logo', models.BooleanField(default=True, verbose_name='логотип Terminal')),
            ],
            options={
                'verbose_name': 'Доставка и оплата',
                'verbose_name_plural': 'Доставка и оплата',
            },
        ),
    ]
