# Generated by Django 3.2.4 on 2022-01-21 11:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_article_delivery_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery_article',
            options={'ordering': ['order'], 'verbose_name': 'Список статей доставки и оплаты', 'verbose_name_plural': 'Списки статей доставки и оплаты'},
        ),
        migrations.AlterModelOptions(
            name='delivery_columns',
            options={'ordering': ['order'], 'verbose_name': 'Столбец', 'verbose_name_plural': 'Столбцы'},
        ),
        migrations.AddField(
            model_name='delivery_article',
            name='bold_text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Жирный текст под таблицей'),
        ),
        migrations.AddField(
            model_name='delivery_article',
            name='bold_text_fr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Жирный текст под таблицей'),
        ),
        migrations.AddField(
            model_name='delivery_article',
            name='bold_text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Жирный текст под таблицей'),
        ),
        migrations.AddField(
            model_name='delivery_article',
            name='country_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='delivery_article',
            name='country_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='delivery_article',
            name='country_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='delivery_article',
            name='grey_text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Серый текст под таблицей'),
        ),
        migrations.AddField(
            model_name='delivery_article',
            name='grey_text_fr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Серый текст под таблицей'),
        ),
        migrations.AddField(
            model_name='delivery_article',
            name='grey_text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Серый текст под таблицей'),
        ),
        migrations.AddField(
            model_name='delivery_article',
            name='intro_text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Вступительный текст'),
        ),
        migrations.AddField(
            model_name='delivery_article',
            name='intro_text_fr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Вступительный текст'),
        ),
        migrations.AddField(
            model_name='delivery_article',
            name='intro_text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Вступительный текст'),
        ),
        migrations.AddField(
            model_name='delivery_article',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='delivery_article',
            name='title_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='delivery_article',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='delivery_columns',
            name='first_column_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Первый столбец'),
        ),
        migrations.AddField(
            model_name='delivery_columns',
            name='first_column_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Первый столбец'),
        ),
        migrations.AddField(
            model_name='delivery_columns',
            name='first_column_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Первый столбец'),
        ),
        migrations.AddField(
            model_name='delivery_columns',
            name='order',
            field=models.IntegerField(null=True, verbose_name='Порядок показа'),
        ),
        migrations.AddField(
            model_name='delivery_columns',
            name='second_column_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Второй столбец'),
        ),
        migrations.AddField(
            model_name='delivery_columns',
            name='second_column_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Второй столбец'),
        ),
        migrations.AddField(
            model_name='delivery_columns',
            name='second_column_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Второй столбец'),
        ),
        migrations.AddField(
            model_name='delivery_columns',
            name='third_column_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Третий столбец'),
        ),
        migrations.AddField(
            model_name='delivery_columns',
            name='third_column_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Третий столбец'),
        ),
        migrations.AddField(
            model_name='delivery_columns',
            name='third_column_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Третий столбец'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='bottom_text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Нижний текст'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='bottom_text_fr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Нижний текст'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='bottom_text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Нижний текст'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='delivery_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставка и оплата'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='delivery_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставка и оплата'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='delivery_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставка и оплата'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='description_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='description_fr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='description_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='keywords_fr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='keywords_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='name_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Название раздела'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='name_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Название раздела'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='name_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Название раздела'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='payment_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Оплата'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='payment_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Оплата'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='payment_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Оплата'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='title_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='top_text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Вступительный текст'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='top_text_fr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Вступительный текст'),
        ),
        migrations.AddField(
            model_name='delivery_main',
            name='top_text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Вступительный текст'),
        ),
        migrations.AlterField(
            model_name='delivery_article',
            name='order',
            field=models.IntegerField(null=True, verbose_name='Порядок показа'),
        ),
    ]
