# Generated by Django 3.2.4 on 2022-01-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_delivery_columns_delivery_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_article',
            name='country',
            field=models.CharField(blank=True, max_length=255, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='delivery_article',
            name='country_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='delivery_article',
            name='country_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='delivery_article',
            name='country_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна'),
        ),
    ]
