# Generated by Django 3.2.4 on 2022-01-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='map_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('is_active_ru', models.BooleanField(default=True, verbose_name='Активная')),
                ('is_active_en', models.BooleanField(default=True, verbose_name='Активная')),
                ('is_active_fr', models.BooleanField(default=True, verbose_name='Активная')),
            ],
            options={
                'verbose_name': 'Где купить',
                'verbose_name_plural': 'Где купить',
            },
        ),
    ]
