# Generated by Django 3.2.4 on 2022-01-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map_main',
            name='bottom_text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст под заголовком'),
        ),
        migrations.AddField(
            model_name='map_main',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='map_main',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='map_main',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название в меню'),
        ),
        migrations.AddField(
            model_name='map_main',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='map_main',
            name='title_page',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок страницы'),
        ),
    ]
