# Generated by Django 3.2.4 on 2022-01-25 18:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20220125_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='map_town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(blank=True, max_length=500, null=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Город',
            },
        ),
        migrations.CreateModel(
            name='map_shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True, verbose_name='Название')),
                ('latitude', models.CharField(max_length=500, null=True, verbose_name='Широта')),
                ('longitude', models.CharField(max_length=500, null=True, verbose_name='Долгота')),
                ('info', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст под фото')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_towns', to='map.map_town', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
