# Generated by Django 3.2.4 on 2022-01-25 19:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_map_shop_map_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_shop',
            name='info',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация'),
        ),
    ]
