# Generated by Django 3.2.4 on 2022-01-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_map_shop_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map_shop',
            options={'ordering': ['order'], 'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AddField(
            model_name='map_shop',
            name='order',
            field=models.IntegerField(null=True, verbose_name='Порядок показа'),
        ),
    ]
