# Generated by Django 3.2.4 on 2022-01-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20220125_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map_main',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='map_main',
            name='is_active_en',
        ),
        migrations.RemoveField(
            model_name='map_main',
            name='is_active_fr',
        ),
        migrations.RemoveField(
            model_name='map_main',
            name='is_active_ru',
        ),
    ]
