# Generated by Django 3.2.4 on 2022-01-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20220126_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='map_main',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная'),
        ),
    ]
