# Generated by Django 3.2.4 on 2022-01-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_projects', '0002_auto_20220117_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_page',
            options={'ordering': ['-name'], 'verbose_name': 'Проекты на заказ', 'verbose_name_plural': 'Проекты на заказ'},
        ),
    ]
