# Generated by Django 3.2.4 on 2022-01-17 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_projects', '0004_auto_20220117_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_page',
            options={'verbose_name': 'Проекты на заказ', 'verbose_name_plural': 'Проекты на заказ'},
        ),
        migrations.RemoveField(
            model_name='project_list',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project_list',
            name='project_en',
        ),
        migrations.RemoveField(
            model_name='project_list',
            name='project_fr',
        ),
        migrations.RemoveField(
            model_name='project_list',
            name='project_ru',
        ),
        migrations.AlterField(
            model_name='project_images',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_projects.project_list', verbose_name='Проекты на заказ'),
        ),
    ]
