# Generated by Django 3.2.4 on 2022-01-18 07:55

from django.db import migrations, models
import django_resized.forms
import order_projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('order_projects', '0007_auto_20220117_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_list',
            name='first_display',
            field=models.BooleanField(default=False, unique=True, verbose_name='Первый проект'),
        ),
        migrations.AddField(
            model_name='project_list',
            name='main_photo_sm',
            field=models.ImageField(blank=True, null=True, upload_to=order_projects.models.get_file_path),
        ),
        migrations.AddField(
            model_name='project_list',
            name='main_photo_sm2x',
            field=models.ImageField(blank=True, null=True, upload_to=order_projects.models.get_file_path),
        ),
        migrations.AddField(
            model_name='project_list',
            name='main_photo_xs',
            field=models.ImageField(blank=True, null=True, upload_to=order_projects.models.get_file_path),
        ),
        migrations.AddField(
            model_name='project_list',
            name='main_photo_xs2',
            field=models.ImageField(blank=True, null=True, upload_to=order_projects.models.get_file_path),
        ),
        migrations.AddField(
            model_name='project_list',
            name='main_photo_xxl',
            field=models.ImageField(blank=True, null=True, upload_to=order_projects.models.get_file_path),
        ),
        migrations.AddField(
            model_name='project_list',
            name='product_original_img',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, null=True, quality=80, size=[2400, 1800], upload_to=order_projects.models.get_file_path, verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='project_images',
            name='main_photo_1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=0, size=[1920, 1080], upload_to=order_projects.models.get_file_path),
        ),
    ]
