# Generated by Django 3.2.4 on 2022-01-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_projects', '0008_auto_20220118_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_list',
            old_name='main_photo_xs2',
            new_name='main_photo_xs2x',
        ),
        migrations.RemoveField(
            model_name='project_list',
            name='main_photo_xxl',
        ),
    ]
