# Generated by Django 3.2.4 on 2022-01-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_projects', '0009_auto_20220118_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_images',
            old_name='main_photo_1',
            new_name='product_original_img',
        ),
    ]
