# Generated by Django 3.2.4 on 2022-01-18 13:15

from django.db import migrations
import django_resized.forms
import order_projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('order_projects', '0011_alter_project_list_product_original_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_list',
            old_name='main_photo_sm2x',
            new_name='main_photo_original',
        ),
        migrations.RemoveField(
            model_name='project_images',
            name='product_original_img',
        ),
        migrations.RemoveField(
            model_name='project_list',
            name='product_original_img',
        ),
        migrations.AddField(
            model_name='project_images',
            name='main_photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, null=True, quality=80, size=[1600, 1200], upload_to=order_projects.models.get_file_path, verbose_name='Основное изображение'),
        ),
        migrations.AddField(
            model_name='project_list',
            name='main_photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, null=True, quality=80, size=[2048, 1536], upload_to=order_projects.models.get_file_path, verbose_name='Основное изображение'),
        ),
    ]
