# Generated by Django 3.2.4 on 2022-01-18 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_projects', '0012_auto_20220118_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_images',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='order_projects.project_list', verbose_name='Проекты на заказ'),
        ),
    ]
