# Generated by Django 3.2.4 on 2022-01-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_projects', '0013_alter_project_images_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_page',
            name='another_projects',
            field=models.CharField(blank=True, max_length=255, verbose_name='Стат. перевод - Другие проекты'),
        ),
        migrations.AddField(
            model_name='project_page',
            name='another_projects_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стат. перевод - Другие проекты'),
        ),
        migrations.AddField(
            model_name='project_page',
            name='another_projects_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стат. перевод - Другие проекты'),
        ),
        migrations.AddField(
            model_name='project_page',
            name='another_projects_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стат. перевод - Другие проекты'),
        ),
        migrations.AddField(
            model_name='project_page',
            name='projects',
            field=models.CharField(blank=True, max_length=255, verbose_name='Стат. перевод - Проекты на заказ'),
        ),
        migrations.AddField(
            model_name='project_page',
            name='projects_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стат. перевод - Проекты на заказ'),
        ),
        migrations.AddField(
            model_name='project_page',
            name='projects_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стат. перевод - Проекты на заказ'),
        ),
        migrations.AddField(
            model_name='project_page',
            name='projects_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стат. перевод - Проекты на заказ'),
        ),
    ]
