# Generated by Django 3.2.4 on 2022-01-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_projects', '0014_auto_20220119_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_page',
            name='another_projects',
            field=models.CharField(blank=True, max_length=255, verbose_name='Другие проекты'),
        ),
        migrations.AlterField(
            model_name='project_page',
            name='another_projects_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Другие проекты'),
        ),
        migrations.AlterField(
            model_name='project_page',
            name='another_projects_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Другие проекты'),
        ),
        migrations.AlterField(
            model_name='project_page',
            name='another_projects_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Другие проекты'),
        ),
        migrations.AlterField(
            model_name='project_page',
            name='projects',
            field=models.CharField(blank=True, max_length=255, verbose_name='Проекты на заказ'),
        ),
        migrations.AlterField(
            model_name='project_page',
            name='projects_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проекты на заказ'),
        ),
        migrations.AlterField(
            model_name='project_page',
            name='projects_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проекты на заказ'),
        ),
        migrations.AlterField(
            model_name='project_page',
            name='projects_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проекты на заказ'),
        ),
    ]
