# Generated by Django 3.2.4 on 2022-01-27 15:59

from django.db import migrations, models
import django_resized.forms
import order_projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('order_projects', '0015_auto_20220120_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_page',
            name='promo_photo_md',
            field=models.ImageField(blank=True, null=True, upload_to=order_projects.models.get_file_path),
        ),
        migrations.AddField(
            model_name='project_page',
            name='promo_photo_md2x',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, null=True, quality=80, size=[2048, 1202], upload_to=order_projects.models.get_file_path, verbose_name='Картинка на главной странице'),
        ),
        migrations.AddField(
            model_name='project_page',
            name='promo_photo_xs',
            field=models.ImageField(blank=True, null=True, upload_to=order_projects.models.get_file_path),
        ),
        migrations.AddField(
            model_name='project_page',
            name='promo_photo_xs2x',
            field=models.ImageField(blank=True, null=True, upload_to=order_projects.models.get_file_path),
        ),
    ]
