# Generated by Django 3.2.4 on 2022-01-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_projects', '0017_project_page_last_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_page',
            name='last_projects_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Последние работы (на главной странице)'),
        ),
        migrations.AddField(
            model_name='project_page',
            name='last_projects_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Последние работы (на главной странице)'),
        ),
        migrations.AddField(
            model_name='project_page',
            name='last_projects_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Последние работы (на главной странице)'),
        ),
    ]
