# Generated by Django 3.2.4 on 2022-02-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_projects', '0018_auto_20220127_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_list',
            name='first_display',
        ),
    ]
