# Generated by Django 3.2.4 on 2022-02-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_projects', '0023_remove_project_list_first_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_list',
            name='first_display',
            field=models.BooleanField(default=False, unique=True, verbose_name='Первый проект'),
        ),
    ]
