# Generated by Django 3.2.4 on 2022-01-21 14:25

import contact.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес')),
                ('map_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на карту')),
                ('work_mode', models.CharField(blank=True, max_length=500, null=True, verbose_name='Режим работы')),
                ('first_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый телефон')),
                ('second_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Второй телефон')),
                ('email', models.URLField(blank=True, null=True, verbose_name='Почта')),
                ('main_photo_xl2x', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, null=True, quality=80, size=[3840, 1456], upload_to=contact.models.get_file_path, verbose_name='Картинка в "контактах')),
                ('main_photo_xl', models.ImageField(blank=True, null=True, upload_to=contact.models.get_file_path)),
                ('main_photo_md', models.ImageField(blank=True, null=True, upload_to=contact.models.get_file_path)),
                ('main_photo_md2x', models.ImageField(blank=True, null=True, upload_to=contact.models.get_file_path)),
                ('main_photo_sm', models.ImageField(blank=True, null=True, upload_to=contact.models.get_file_path)),
                ('main_photo_sm2x', models.ImageField(blank=True, null=True, upload_to=contact.models.get_file_path)),
                ('main_photo_xs', models.ImageField(blank=True, null=True, upload_to=contact.models.get_file_path)),
                ('main_photo_xs2x', models.ImageField(blank=True, null=True, upload_to=contact.models.get_file_path)),
                ('main_photo_xl1', models.ImageField(blank=True, null=True, upload_to=contact.models.get_file_path)),
                ('main_photo_xl12x', models.ImageField(blank=True, null=True, upload_to=contact.models.get_file_path)),
            ],
        ),
    ]
