# Generated by Django 3.2.4 on 2022-01-21 14:34

import contact.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_main_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_main',
            name='main_photo_xl2x',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, null=True, quality=80, size=[3840, 1456], upload_to=contact.models.get_file_path, verbose_name='Картинка в "контактах"'),
        ),
    ]
