# Generated by Django 3.2.4 on 2022-01-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_main_main_photo_xl2x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_main',
            name='main_photo_md',
        ),
        migrations.RemoveField(
            model_name='contact_main',
            name='main_photo_md2x',
        ),
        migrations.RemoveField(
            model_name='contact_main',
            name='main_photo_sm',
        ),
        migrations.RemoveField(
            model_name='contact_main',
            name='main_photo_sm2x',
        ),
        migrations.RemoveField(
            model_name='contact_main',
            name='main_photo_xl',
        ),
        migrations.RemoveField(
            model_name='contact_main',
            name='main_photo_xl1',
        ),
        migrations.RemoveField(
            model_name='contact_main',
            name='main_photo_xl12x',
        ),
        migrations.RemoveField(
            model_name='contact_main',
            name='main_photo_xl2x',
        ),
        migrations.RemoveField(
            model_name='contact_main',
            name='main_photo_xs',
        ),
        migrations.RemoveField(
            model_name='contact_main',
            name='main_photo_xs2x',
        ),
    ]
