# Generated by Django 3.2.4 on 2022-01-24 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20220124_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_social_networks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True, verbose_name='Порядок показа')),
                ('social_network_url', models.URLField(verbose_name='Ссылка на социальную сеть')),
                ('social_network_type', models.CharField(blank=True, choices=[('1', 'WhatsApp'), ('2', 'Telegram'), ('3', 'Be'), ('4', 'Facebook'), ('5', 'Vk'), ('6', 'Instagram'), ('7', 'YouTube')], max_length=100, verbose_name='Тип социальной сети')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_networks', to='contact.contact_main', verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Соц. сети в контактах',
                'verbose_name_plural': 'Соц. сети в контактах',
            },
        ),
    ]
