# Generated by Django 3.2.4 on 2022-01-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contact_social_networks'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_main',
            name='address_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='address_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='address_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='work_mode_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Режим работы'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='work_mode_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Режим работы'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='work_mode_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Режим работы'),
        ),
    ]
