# Generated by Django 3.2.4 on 2022-01-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_contact_social_networks_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_main',
            options={'ordering': ['order'], 'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AddField(
            model_name='contact_main',
            name='order',
            field=models.IntegerField(null=True, verbose_name='Порядок показа'),
        ),
    ]
