# Generated by Django 3.2.4 on 2022-01-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20220124_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_social_networks',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для проверки'),
        ),
    ]
