# Generated by Django 3.2.4 on 2022-01-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_contact_social_networks_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_social_networks',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для проверки'),
        ),
        migrations.AddField(
            model_name='contact_social_networks',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для проверки'),
        ),
        migrations.AddField(
            model_name='contact_social_networks',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для проверки'),
        ),
    ]
