# Generated by Django 3.2.4 on 2022-01-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20220124_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_main',
            name='address_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='address_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='address_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='work_mode_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Режим работы'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='work_mode_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Режим работы'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='work_mode_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Режим работы'),
        ),
        migrations.AddField(
            model_name='contact_social_networks',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для проверки'),
        ),
        migrations.AddField(
            model_name='contact_social_networks',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для проверки'),
        ),
        migrations.AddField(
            model_name='contact_social_networks',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок для проверки'),
        ),
    ]
