# Generated by Django 3.2.4 on 2022-01-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_auto_20220124_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_social_networks',
            name='title',
        ),
        migrations.RemoveField(
            model_name='contact_social_networks',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='contact_social_networks',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='contact_social_networks',
            name='title_ru',
        ),
    ]
