# Generated by Django 3.2.4 on 2022-01-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_auto_20220124_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_main',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.RemoveField(
            model_name='contact_main',
            name='order',
        ),
    ]
