# Generated by Django 3.2.4 on 2022-01-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_auto_20220124_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_social_networks',
            name='social_network_type',
            field=models.CharField(blank=True, choices=[('1', 'WhatsApp'), ('2', 'Telegram'), ('3', 'Be'), ('4', 'Facebook'), ('5', 'Vk'), ('6', 'Instagram'), ('7', 'YouTube')], max_length=100, unique=True, verbose_name='Тип социальной сети'),
        ),
    ]
