# Generated by Django 3.2.4 on 2022-01-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0017_alter_contact_main_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_main',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='description_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='description_fr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='description_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='intro_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Приходите в гости!'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='intro_title_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Приходите в гости!'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='intro_title_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Приходите в гости!'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='intro_title_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Приходите в гости!'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='keywords_fr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='keywords_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название раздела в меню'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='title_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='title_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок'),
        ),
    ]
