# Generated by Django 3.2.4 on 2022-01-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0018_auto_20220124_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_main',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название раздела в меню'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='name_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название раздела в меню'),
        ),
        migrations.AddField(
            model_name='contact_main',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название раздела в меню'),
        ),
    ]
