# Generated by Django 3.2.4 on 2022-01-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0019_auto_20220124_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=500, verbose_name='Заголовок формы')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Заголовок поля ФИО')),
                ('email', models.CharField(blank=True, max_length=500, verbose_name='Заголовок поля электронная почта')),
                ('number', models.CharField(blank=True, max_length=500, verbose_name='Заголовок поля телефон')),
                ('message', models.TextField(blank=True, max_length=500, verbose_name='Заголовок поля сообщение')),
                ('send', models.CharField(blank=True, max_length=500, verbose_name='Заголовок кнопки')),
                ('success', models.CharField(blank=True, max_length=500, verbose_name='Успешная отправка')),
                ('error', models.CharField(blank=True, max_length=500, verbose_name='Неуспешная отправка')),
            ],
            options={
                'verbose_name': 'Письмо нам',
                'verbose_name_plural': 'Письмо нам',
            },
        ),
    ]
