# Generated by Django 3.2.4 on 2022-01-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0020_contact_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_form',
            name='email_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок поля электронная почта'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='email_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок поля электронная почта'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='email_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок поля электронная почта'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='error_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Неуспешная отправка'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='error_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Неуспешная отправка'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='error_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Неуспешная отправка'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='heading_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок формы'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='heading_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок формы'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='heading_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок формы'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='message_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Заголовок поля сообщение'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='message_fr',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Заголовок поля сообщение'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='message_ru',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Заголовок поля сообщение'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок поля ФИО'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='name_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок поля ФИО'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок поля ФИО'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='number_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок поля телефон'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='number_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок поля телефон'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='number_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок поля телефон'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='send_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок кнопки'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='send_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок кнопки'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='send_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок кнопки'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='success_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Успешная отправка'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='success_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Успешная отправка'),
        ),
        migrations.AddField(
            model_name='contact_form',
            name='success_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Успешная отправка'),
        ),
    ]
