# Generated by Django 3.2.4 on 2021-12-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_item_photos_main_photo_xxl2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='item',
            field=models.ManyToManyField(blank=True, to='shop.Item', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='shop.SubCategory', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='item',
            field=models.ManyToManyField(blank=True, to='shop.Item', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='shop.SubCategory', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='item',
            name='connected_items',
            field=models.ManyToManyField(blank=True, related_name='_shop_item_connected_items_+', to='shop.Item', verbose_name='Связанные товары'),
        ),
    ]
