# Generated by Django 3.2.4 on 2021-12-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20211220_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='item',
            field=models.ManyToManyField(blank=True, to='shop.Item', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='shop.SubCategory', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='item',
            field=models.ManyToManyField(blank=True, to='shop.Item', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='shop.SubCategory', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='item',
            name='connected_items',
            field=models.ManyToManyField(blank=True, related_name='_shop_item_connected_items_+', to='shop.Item', verbose_name='Связанные товары'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='URL генерируется автоматически из названия раздела, но может быть задан вручную', verbose_name='URL'),
        ),
    ]
