# Generated by Django 3.2.4 on 2021-12-23 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20211220_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='item',
            field=models.ManyToManyField(blank=True, to='shop.Item', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='shop.SubCategory', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='item',
            field=models.ManyToManyField(blank=True, to='shop.Item', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='shop.SubCategory', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='item',
            name='connected_items',
            field=models.ManyToManyField(blank=True, related_name='_shop_item_connected_items_+', to='shop.Item', verbose_name='Связанные товары'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_category', to='shop.category', verbose_name='Категория'),
        ),
    ]
