# Generated by Django 3.2.4 on 2021-12-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20211223_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='shop.SubCategory', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='shop.SubCategory', verbose_name='Категории'),
        ),
    ]
