# Generated by Django 3.2.4 on 2021-12-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20211228_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all', models.CharField(blank=True, max_length=200, verbose_name='Заголовок ссылки всех товаров')),
                ('all_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок ссылки всех товаров')),
                ('all_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок ссылки всех товаров')),
                ('all_fr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок ссылки всех товаров')),
            ],
        ),
    ]
