# Generated by Django 3.2.4 on 2021-12-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_shop_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_page',
            name='alphabet',
            field=models.CharField(blank=True, max_length=255, verbose_name='По алфавиту'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='alphabet_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='По алфавиту'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='alphabet_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='По алфавиту'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='alphabet_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='По алфавиту'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='decrease',
            field=models.CharField(blank=True, max_length=255, verbose_name='Цена по возрастанию'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='decrease_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена по возрастанию'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='decrease_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена по возрастанию'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='decrease_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена по возрастанию'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='difficult',
            field=models.CharField(blank=True, max_length=255, verbose_name='По сложности'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='difficult_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='По сложности'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='difficult_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='По сложности'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='difficult_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='По сложности'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='increase',
            field=models.CharField(blank=True, max_length=255, verbose_name='Цена по возрастанию'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='increase_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена по возрастанию'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='increase_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена по возрастанию'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='increase_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена по возрастанию'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='no_items',
            field=models.CharField(blank=True, max_length=255, verbose_name='Товары не найдены'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='no_items_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Товары не найдены'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='no_items_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Товары не найдены'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='no_items_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Товары не найдены'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='popular',
            field=models.CharField(blank=True, max_length=255, verbose_name='По популярности'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='popular_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='По популярности'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='popular_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='По популярности'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='popular_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='По популярности'),
        ),
    ]
