# Generated by Django 3.2.4 on 2021-12-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20211230_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_page',
            name='decrease',
            field=models.CharField(blank=True, max_length=255, verbose_name='Цена по убыванию'),
        ),
        migrations.AlterField(
            model_name='shop_page',
            name='decrease_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена по убыванию'),
        ),
        migrations.AlterField(
            model_name='shop_page',
            name='decrease_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена по убыванию'),
        ),
        migrations.AlterField(
            model_name='shop_page',
            name='decrease_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена по убыванию'),
        ),
    ]
