# Generated by Django 3.2.4 on 2021-12-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20211230_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_page',
            name='cart',
            field=models.CharField(blank=True, max_length=255, verbose_name='В корзину'),
        ),
    ]
