# Generated by Django 3.2.4 on 2021-12-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_shop_page_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_page',
            name='cart_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='В корзину'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='cart_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='В корзину'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='cart_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='В корзину'),
        ),
    ]
