# Generated by Django 3.2.4 on 2022-01-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20211230_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop_page',
            options={'verbose_name': 'Статический перевод', 'verbose_name_plural': 'Статические переводы'},
        ),
    ]
