# Generated by Django 3.2.4 on 2022-01-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_shop_page_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_page',
            name='another_items',
            field=models.CharField(blank=True, max_length=255, verbose_name='Этот товар в других форматах'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='assembly_time',
            field=models.CharField(blank=True, max_length=255, verbose_name='Время сборки'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='compare',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сравнить'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='complexity',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='delivery',
            field=models.CharField(blank=True, max_length=255, verbose_name='Доставка и оплата'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='figure_size',
            field=models.CharField(blank=True, max_length=255, verbose_name='Размер фигуры'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='megabyte',
            field=models.CharField(blank=True, max_length=255, verbose_name='Мегабайт документа'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Количество листов'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='to_do',
            field=models.CharField(blank=True, max_length=255, verbose_name='Что с этим делать'),
        ),
    ]
