# Generated by Django 3.2.4 on 2022-01-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20220105_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_page',
            name='another_items_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Этот товар в других форматах'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='another_items_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Этот товар в других форматах'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='another_items_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Этот товар в других форматах'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='assembly_time_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время сборки'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='assembly_time_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время сборки'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='assembly_time_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время сборки'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='compare_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сравнить'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='compare_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сравнить'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='compare_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сравнить'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='complexity_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='complexity_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='complexity_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='delivery_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставка и оплата'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='delivery_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставка и оплата'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='delivery_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставка и оплата'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='figure_size_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер фигуры'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='figure_size_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер фигуры'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='figure_size_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер фигуры'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='megabyte_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мегабайт документа'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='megabyte_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мегабайт документа'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='megabyte_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мегабайт документа'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='number_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество листов'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='number_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество листов'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='number_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество листов'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='to_do_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Что с этим делать'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='to_do_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Что с этим делать'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='to_do_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Что с этим делать'),
        ),
    ]
