# Generated by Django 3.2.4 on 2022-01-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20220105_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_page',
            name='another_models',
            field=models.CharField(blank=True, max_length=255, verbose_name='Другие модели'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='another_models_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Другие модели'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='another_models_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Другие модели'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='another_models_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Другие модели'),
        ),
    ]
