# Generated by Django 3.2.4 on 2022-01-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20220105_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_page',
            name='see_more',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подробнее'),
        ),
    ]
