# Generated by Django 3.2.4 on 2022-01-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_shop_page_see_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_page',
            name='see_more_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подробнее'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='see_more_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подробнее'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='see_more_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подробнее'),
        ),
    ]
