# Generated by Django 3.2.4 on 2022-01-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20220105_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_page',
            name='color',
            field=models.CharField(blank=True, max_length=255, verbose_name='Цвет'),
        ),
    ]
