# Generated by Django 3.2.4 on 2022-01-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_shop_page_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_page',
            name='adding_cart',
            field=models.CharField(blank=True, max_length=255, verbose_name='В корзине'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='adding_cart_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='В корзине'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='adding_cart_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='В корзине'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='adding_cart_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='В корзине'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='color_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='color_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='color_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет'),
        ),
    ]
