# Generated by Django 3.2.4 on 2022-01-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_item_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_page',
            name='new_start',
            field=models.CharField(blank=True, max_length=255, verbose_name='Начать сначала'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='new_start_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Начать сначала'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='new_start_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Начать сначала'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='new_start_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Начать сначала'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='page_not_found',
            field=models.CharField(blank=True, max_length=255, verbose_name='Страница не найдена'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='page_not_found_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страница не найдена'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='page_not_found_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страница не найдена'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='page_not_found_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страница не найдена'),
        ),
    ]
