# Generated by Django 3.2.4 on 2022-01-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_itemcountviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='itemcountviews',
        ),
    ]
