# Generated by Django 3.2.4 on 2022-01-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_delete_itemcountviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров товара'),
        ),
    ]
