# Generated by Django 3.2.4 on 2022-01-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_item_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='views',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество просмотров товара'),
        ),
    ]
