# Generated by Django 3.2.4 on 2022-01-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_auto_20220110_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='amount_en',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='amount_fr',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='amount_ru',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='amount_en',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='amount_fr',
        ),
        migrations.AddField(
            model_name='discount',
            name='amount_eur',
            field=models.FloatField(blank=True, null=True, verbose_name='Величина скидки евро'),
        ),
        migrations.AddField(
            model_name='discount',
            name='amount_usd',
            field=models.FloatField(blank=True, null=True, verbose_name='Величина скидки доллара'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='amount_ru',
            field=models.FloatField(blank=True, null=True, verbose_name='Величина скидки рубля'),
        ),
    ]
