# Generated by Django 3.2.4 on 2022-01-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_auto_20220111_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_page',
            name='of',
            field=models.CharField(blank=True, max_length=255, verbose_name='Из (сложность)'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='of_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Из (сложность)'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='of_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Из (сложность)'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='of_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Из (сложность)'),
        ),
    ]
