# Generated by Django 3.2.4 on 2022-01-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_auto_20220117_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_page',
            name='shop',
            field=models.CharField(blank=True, max_length=255, verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='shop_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='shop_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='shop_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Магазин'),
        ),
    ]
