# Generated by Django 3.2.4 on 2022-01-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_auto_20220117_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_page',
            name='another_projects',
            field=models.CharField(blank=True, max_length=255, verbose_name='Другие проекты'),
        ),
    ]
