# Generated by Django 3.2.4 on 2022-01-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_shop_page_another_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_page',
            name='another_projects_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Другие проекты'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='another_projects_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Другие проекты'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='another_projects_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Другие проекты'),
        ),
    ]
