# Generated by Django 3.2.4 on 2022-01-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_auto_20220118_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_page',
            name='advice',
            field=models.CharField(blank=True, max_length=255, verbose_name='Советы по сборке'),
        ),
    ]
