# Generated by Django 3.2.4 on 2022-01-19 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_auto_20220119_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_page',
            name='advice',
        ),
        migrations.RemoveField(
            model_name='shop_page',
            name='advice_en',
        ),
        migrations.RemoveField(
            model_name='shop_page',
            name='advice_fr',
        ),
        migrations.RemoveField(
            model_name='shop_page',
            name='advice_ru',
        ),
        migrations.RemoveField(
            model_name='shop_page',
            name='another_projects',
        ),
        migrations.RemoveField(
            model_name='shop_page',
            name='another_projects_en',
        ),
        migrations.RemoveField(
            model_name='shop_page',
            name='another_projects_fr',
        ),
        migrations.RemoveField(
            model_name='shop_page',
            name='another_projects_ru',
        ),
        migrations.RemoveField(
            model_name='shop_page',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='shop_page',
            name='projects_en',
        ),
        migrations.RemoveField(
            model_name='shop_page',
            name='projects_fr',
        ),
        migrations.RemoveField(
            model_name='shop_page',
            name='projects_ru',
        ),
    ]
