# Generated by Django 3.2.4 on 2022-02-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_auto_20220127_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name_lower',
            field=models.CharField(max_length=500, null=True, verbose_name='Название в нижнем регистре'),
        ),
    ]
