# Generated by Django 3.2.4 on 2022-02-10 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_item_name_lower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='subcategory',
        ),
    ]
