# Generated by Django 3.2.4 on 2022-02-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_remove_discount_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='subcategory',
        ),
    ]
