# Generated by Django 3.2.4 on 2022-03-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_alter_item_basket_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_page',
            name='check_order',
            field=models.CharField(blank=True, max_length=255, verbose_name='Оформить заказ'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='check_order_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Оформить заказ'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='check_order_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Оформить заказ'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='check_order_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Оформить заказ'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='less',
            field=models.CharField(blank=True, max_length=255, verbose_name='Меньше'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='less_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Меньше'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='less_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Меньше'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='less_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Меньше'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='more',
            field=models.CharField(blank=True, max_length=255, verbose_name='Больше'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='more_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Больше'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='more_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Больше'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='more_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Больше'),
        ),
    ]
