# Generated by Django 3.2.4 on 2022-03-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_auto_20220303_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_page',
            name='promo_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Промо-код'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='promo_code_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Промо-код'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='promo_code_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Промо-код'),
        ),
        migrations.AddField(
            model_name='shop_page',
            name='promo_code_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Промо-код'),
        ),
    ]
