# Generated by Django 3.2.4 on 2022-01-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название в меню')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название в меню')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название в меню')),
                ('name_fr', models.CharField(max_length=255, null=True, verbose_name='Название в меню')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
