# Generated by Django 3.2.4 on 2022-01-25 14:15

import about.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20220125_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_main',
            name='bottom_text',
            field=models.CharField(max_length=500, null=True, verbose_name='Текст под заголовком страницы'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='grey_text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Подпись под фото'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='main_photo_md',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.get_file_path),
        ),
        migrations.AddField(
            model_name='about_main',
            name='main_photo_md2x',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.get_file_path),
        ),
        migrations.AddField(
            model_name='about_main',
            name='main_photo_sm',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.get_file_path),
        ),
        migrations.AddField(
            model_name='about_main',
            name='main_photo_sm2x',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.get_file_path),
        ),
        migrations.AddField(
            model_name='about_main',
            name='main_photo_xl',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.get_file_path),
        ),
        migrations.AddField(
            model_name='about_main',
            name='main_photo_xl1',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.get_file_path),
        ),
        migrations.AddField(
            model_name='about_main',
            name='main_photo_xl12x',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.get_file_path),
        ),
        migrations.AddField(
            model_name='about_main',
            name='main_photo_xl2x',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, null=True, quality=80, size=[3840, 1456], upload_to=about.models.get_file_path, verbose_name='Картинка в "О нас"'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='main_photo_xs',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.get_file_path),
        ),
        migrations.AddField(
            model_name='about_main',
            name='main_photo_xs2x',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.get_file_path),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_page',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок страницы'),
        ),
    ]
