# Generated by Django 3.2.4 on 2022-01-25 14:31

import about.models
import ckeditor.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20220125_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_main',
            old_name='grey_text',
            new_name='grey_text_photo',
        ),
        migrations.RemoveField(
            model_name='about_main',
            name='main_photo_xl1',
        ),
        migrations.RemoveField(
            model_name='about_main',
            name='main_photo_xl12x',
        ),
        migrations.AddField(
            model_name='about_main',
            name='bottom_text_photo',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст под фото'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_author',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок "Наши авторы"'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_create_model',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок "Как мы создаём модели"'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_press',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок "Мы в прессе"'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_reward',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок "Награды"'),
        ),
        migrations.AlterField(
            model_name='about_main',
            name='main_photo_xl2x',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, null=True, quality=80, size=[3840, 2560], upload_to=about.models.get_file_path, verbose_name='Картинка в "О нас"'),
        ),
    ]
