# Generated by Django 3.2.4 on 2022-01-25 15:28

import about.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20220125_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True, verbose_name='Порядок показа')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('text', models.CharField(max_length=500, null=True, verbose_name='Текст под заголовком')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_rewards', to='about.about_main', verbose_name='Награды')),
            ],
            options={
                'verbose_name': 'Награды',
                'verbose_name_plural': 'Награды',
            },
        ),
        migrations.CreateModel(
            name='about_press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True, verbose_name='Порядок показа')),
                ('main_logo_lg2x', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, null=True, quality=80, size=[256, 256], upload_to=about.models.get_file_path, verbose_name='Логотип в "Мы в прессе"')),
                ('main_logo_lg', models.ImageField(blank=True, null=True, upload_to=about.models.get_file_path)),
                ('main_logo_xs', models.ImageField(blank=True, null=True, upload_to=about.models.get_file_path)),
                ('main_logo_xs2x', models.ImageField(blank=True, null=True, upload_to=about.models.get_file_path)),
                ('published', models.DateField(verbose_name='Дата публикации')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_press', to='about.about_main', verbose_name='Мы в прессе')),
            ],
            options={
                'verbose_name': 'Мы в прессе',
                'verbose_name_plural': 'Мы в прессе',
            },
        ),
        migrations.CreateModel(
            name='about_author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True, verbose_name='Порядок показа')),
                ('full_name', models.CharField(max_length=500, null=True, verbose_name='Ф.И.О.')),
                ('position', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('text', ckeditor.fields.RichTextField(null=True, verbose_name='Текст')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_authors', to='about.about_main', verbose_name='Наши авторы')),
            ],
            options={
                'verbose_name': 'Наши авторы',
                'verbose_name_plural': 'Наши авторы',
            },
        ),
    ]
