# Generated by Django 3.2.4 on 2022-01-25 15:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20220125_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_author',
            name='full_name_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Ф.И.О.'),
        ),
        migrations.AddField(
            model_name='about_author',
            name='full_name_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Ф.И.О.'),
        ),
        migrations.AddField(
            model_name='about_author',
            name='full_name_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Ф.И.О.'),
        ),
        migrations.AddField(
            model_name='about_author',
            name='position_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='about_author',
            name='position_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='about_author',
            name='position_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='about_author',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='about_author',
            name='text_fr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='about_author',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='bottom_text_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Текст под заголовком страницы'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='bottom_text_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Текст под заголовком страницы'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='bottom_text_photo_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст под фото'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='bottom_text_photo_fr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст под фото'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='bottom_text_photo_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст под фото'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='bottom_text_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Текст под заголовком страницы'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='description_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='description_fr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='description_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='grey_text_photo_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Подпись под фото'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='grey_text_photo_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Подпись под фото'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='grey_text_photo_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Подпись под фото'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='keywords_fr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='keywords_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='number_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись под цифрой'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='number_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись под цифрой'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='number_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись под цифрой'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_author_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок "Наши авторы"'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_author_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок "Наши авторы"'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_author_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок "Наши авторы"'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_create_model_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок "Как мы создаём модели"'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_create_model_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок "Как мы создаём модели"'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_create_model_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок "Как мы создаём модели"'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_page_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_page_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_page_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_press_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок "Мы в прессе"'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_press_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок "Мы в прессе"'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_press_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок "Мы в прессе"'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_reward_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок "Награды"'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_reward_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок "Награды"'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_reward_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок "Награды"'),
        ),
        migrations.AddField(
            model_name='about_main',
            name='title_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='about_press',
            name='published_en',
            field=models.DateField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='about_press',
            name='published_fr',
            field=models.DateField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='about_press',
            name='published_ru',
            field=models.DateField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='about_press',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='about_press',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='about_press',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='about_reward',
            name='text_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Текст под заголовком'),
        ),
        migrations.AddField(
            model_name='about_reward',
            name='text_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Текст под заголовком'),
        ),
        migrations.AddField(
            model_name='about_reward',
            name='text_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Текст под заголовком'),
        ),
        migrations.AddField(
            model_name='about_reward',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='about_reward',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='about_reward',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
