# Generated by Django 3.2.4 on 2022-01-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20220125_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_author',
            options={'ordering': ['order'], 'verbose_name': 'Наши авторы', 'verbose_name_plural': 'Наши авторы'},
        ),
        migrations.AlterModelOptions(
            name='about_press',
            options={'ordering': ['order'], 'verbose_name': 'Мы в прессе', 'verbose_name_plural': 'Мы в прессе'},
        ),
        migrations.AlterModelOptions(
            name='about_reward',
            options={'ordering': ['order'], 'verbose_name': 'Награды', 'verbose_name_plural': 'Награды'},
        ),
    ]
