# Generated by Django 3.2.4 on 2022-01-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20220125_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_main',
            name='video_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на видео Vimeo'),
        ),
    ]
