# Generated by Django 3.2.4 on 2022-01-26 10:49

import about.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_about_main_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_author',
            name='author_photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, null=True, quality=80, size=[1280, 680], upload_to=about.models.get_file_path, verbose_name='Фото'),
        ),
    ]
