# Generated by Django 3.2.4 on 2022-01-30 20:20

import about.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_auto_20220130_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_author',
            name='index_photo_lg',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.get_file_path),
        ),
        migrations.AddField(
            model_name='about_author',
            name='index_photo_lg2x',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, null=True, quality=80, size=[2048, 1202], upload_to=about.models.get_file_path, verbose_name='Картинка на главной странице'),
        ),
        migrations.AddField(
            model_name='about_author',
            name='index_photo_xs',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.get_file_path),
        ),
        migrations.AddField(
            model_name='about_author',
            name='index_photo_xs2x',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.get_file_path),
        ),
    ]
