# Generated by Django 3.2.4 on 2022-01-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='footer_elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_love', models.CharField(max_length=255, null=True, verbose_name='Сделано с любовью в')),
                ('with_love_ru', models.CharField(max_length=255, null=True, verbose_name='Сделано с любовью в')),
                ('with_love_en', models.CharField(max_length=255, null=True, verbose_name='Сделано с любовью в')),
                ('with_love_fr', models.CharField(max_length=255, null=True, verbose_name='Сделано с любовью в')),
                ('year', models.PositiveIntegerField(default=1, null=True, verbose_name='Текущий год')),
            ],
            options={
                'verbose_name': 'Текущий год и копирайт',
                'verbose_name_plural': 'Текущий год и копирайт',
            },
        ),
    ]
