# Generated by Django 3.2.4 on 2022-01-26 18:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='info',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация'),
        ),
    ]
