# Generated by Django 3.2.4 on 2022-01-26 19:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220126_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(blank=True, max_length=1000, verbose_name='Ключевые слова')),
                ('keywords_ru', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ключевые слова')),
                ('keywords_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ключевые слова')),
                ('keywords_fr', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ключевые слова')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('description_ru', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('description_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('description_fr', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Заголовок')),
                ('title_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок')),
                ('title_fr', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_fr', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст после названия')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст после названия')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Текст после названия')),
                ('text_fr', models.TextField(blank=True, null=True, verbose_name='Текст после названия')),
                ('info', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация')),
                ('info_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация')),
                ('info_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация')),
                ('info_fr', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Политика персональных данных',
                'verbose_name_plural': 'Политика персональных данных',
            },
        ),
    ]
