# Generated by Django 3.2.4 on 2022-01-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='text',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='text_fr',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='text_ru',
        ),
    ]
