# Generated by Django 3.2.4 on 2022-01-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220126_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer_elements',
            options={'verbose_name': 'Копирайт', 'verbose_name_plural': 'Копирайт'},
        ),
        migrations.RemoveField(
            model_name='footer_elements',
            name='year',
        ),
    ]
