BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX

                    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        BBB B BB BBBBBBBBBB
                            XXXXXXX XXXXXXXX
                                    XXXXXXXXXXXXX
                                
                            XXXXXXXXX
                        BBBBBB
                    XXXXXXXXX

                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                        BBB BBBBBBBB BB BBBBBBBBBB
                            BB BBBBBBBBBBBBBBBBBB
                                XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                    XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBX
                                       XXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXX
                            BBBBB
                        BBBBBB
                    XXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXXXXXXXXXXXXXXXXXXXXXXX
                       BBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXX
                    XX XXXXXXXX
                        XXX XXXX
                XXXXX
                BBB B BB BBBBBBBBBBBBB
                    XXX XXXXXXXXXXXXXXXXXXXXXXXX
                       BB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBB
                        XXXXXXXXXXXXXXXXXXXXXXXXX
                         BBBBBXX
                        XX XXXXXXXXXXXX
                    XXXXX
                BBBBBB
            XXXXX
        XXXXXX

    XXXXXX

    XX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX
        XXXXXXXXXX X XXXXXX XXXXXXX
        XXXXXX XX XXXXXXXXXXXX
BBBBBBBB
BBBBB BBBBBBB
    XXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXX
            XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX X XXX
        X

        XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
            XXX
        XX
    XXXXXXXXX
    XXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXX XXXX X
            XX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXX XXXXX
            X
        XX

        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXX XXXX X
            XX XXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXX XXXXX
            X
        XX



    XXXXXXXXX
BBBBBBBB