# Generated by Django 3.2.4 on 2022-01-27 12:09

import django.core.validators
from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_main',
            name='figure_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст между фигурами'),
        ),
        migrations.AddField(
            model_name='index_main',
            name='figure_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Заголовок между фигурами'),
        ),
        migrations.AddField(
            model_name='index_main',
            name='first_figure_button_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка кнопки первой фигуры'),
        ),
        migrations.AddField(
            model_name='index_main',
            name='first_figure_button_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название кнопки первой фигуры'),
        ),
        migrations.AddField(
            model_name='index_main',
            name='fourth_figure_button_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка кнопки четвертой фигуры'),
        ),
        migrations.AddField(
            model_name='index_main',
            name='fourth_figure_button_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название кнопки четвертой фигуры'),
        ),
        migrations.AddField(
            model_name='index_main',
            name='model_file',
            field=models.FileField(blank=True, help_text='Формат файла: pdf. Ограничение размера: 1 Мбайт.', upload_to=index.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Файл модели'),
        ),
        migrations.AddField(
            model_name='index_main',
            name='proud_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст под заголовком "Мы гордимся"'),
        ),
        migrations.AddField(
            model_name='index_main',
            name='proud_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок "Мы гордимся"'),
        ),
        migrations.AddField(
            model_name='index_main',
            name='second_figure_button_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка кнопки второй фигуры'),
        ),
        migrations.AddField(
            model_name='index_main',
            name='second_figure_button_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название кнопки второй фигуры'),
        ),
        migrations.AddField(
            model_name='index_main',
            name='third_figure_button_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка кнопки третьей фигуры'),
        ),
        migrations.AddField(
            model_name='index_main',
            name='third_figure_button_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название кнопки третьей фигуры'),
        ),
        migrations.AddField(
            model_name='index_main',
            name='title_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок ссылки скачивания'),
        ),
        migrations.AlterField(
            model_name='index_main',
            name='title_page',
            field=models.CharField(blank=True, max_length=500, verbose_name='Заголовок страницы'),
        ),
    ]
