# Generated by Django 3.2.4 on 2022-01-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20220127_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_point',
            options={'ordering': ['order'], 'verbose_name': 'Пункты списка', 'verbose_name_plural': 'Пункты списка'},
        ),
    ]
