# Generated by Django 3.2.4 on 2022-01-27 17:08

from django.db import migrations, models
import django_resized.forms
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20220127_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_point',
            name='promo_photo_md',
        ),
        migrations.RemoveField(
            model_name='order_point',
            name='promo_photo_md2x',
        ),
        migrations.RemoveField(
            model_name='order_point',
            name='promo_photo_xs',
        ),
        migrations.RemoveField(
            model_name='order_point',
            name='promo_photo_xs2x',
        ),
        migrations.AddField(
            model_name='index_main',
            name='first_figure_sticker_xs',
            field=models.ImageField(blank=True, null=True, upload_to=index.models.get_file_path),
        ),
        migrations.AddField(
            model_name='index_main',
            name='first_figure_sticker_xs2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, null=True, quality=80, size=[640, 1080], upload_to=index.models.get_file_path, verbose_name='Картинка первой фигуры'),
        ),
        migrations.AddField(
            model_name='index_main',
            name='fourth_figure_sticker_xs',
            field=models.ImageField(blank=True, null=True, upload_to=index.models.get_file_path),
        ),
        migrations.AddField(
            model_name='index_main',
            name='fourth_figure_sticker_xs2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, null=True, quality=80, size=[600, 801], upload_to=index.models.get_file_path, verbose_name='Картинка четвертой фигуры'),
        ),
        migrations.AddField(
            model_name='index_main',
            name='second_figure_sticker_xs',
            field=models.ImageField(blank=True, null=True, upload_to=index.models.get_file_path),
        ),
        migrations.AddField(
            model_name='index_main',
            name='second_figure_sticker_xs2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, null=True, quality=80, size=[600, 788], upload_to=index.models.get_file_path, verbose_name='Картинка второй фигуры'),
        ),
        migrations.AddField(
            model_name='index_main',
            name='third_figure_sticker_xs',
            field=models.ImageField(blank=True, null=True, upload_to=index.models.get_file_path),
        ),
        migrations.AddField(
            model_name='index_main',
            name='third_figure_sticker_xs2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, null=True, quality=80, size=[640, 758], upload_to=index.models.get_file_path, verbose_name='Картинка третьей фигуры'),
        ),
        migrations.AlterField(
            model_name='index_main',
            name='title_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='Текст под заголовком'),
        ),
        migrations.AlterField(
            model_name='index_main',
            name='title_text_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст под заголовком'),
        ),
        migrations.AlterField(
            model_name='index_main',
            name='title_text_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст под заголовком'),
        ),
        migrations.AlterField(
            model_name='index_main',
            name='title_text_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст под заголовком'),
        ),
    ]
