# Generated by Django 3.2.4 on 2022-01-27 18:41

from django.db import migrations, models
import django_resized.forms
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20220127_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_main',
            name='proud_picture_xs',
            field=models.ImageField(blank=True, null=True, upload_to=index.models.get_file_path),
        ),
        migrations.AddField(
            model_name='index_main',
            name='proud_picture_xs2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, null=True, quality=80, size=[992, 658], upload_to=index.models.get_file_path, verbose_name='Картинка "Мы гордимся"'),
        ),
    ]
