# Generated by Django 3.2.4 on 2022-01-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_index_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_translate',
            name='catalog_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Смотреть в каталог'),
        ),
        migrations.AddField(
            model_name='index_translate',
            name='catalog_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Смотреть в каталог'),
        ),
        migrations.AddField(
            model_name='index_translate',
            name='catalog_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Смотреть в каталог'),
        ),
        migrations.AddField(
            model_name='index_translate',
            name='shop_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Перейти в магазин'),
        ),
        migrations.AddField(
            model_name='index_translate',
            name='shop_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Перейти в магазин'),
        ),
        migrations.AddField(
            model_name='index_translate',
            name='shop_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Перейти в магазин'),
        ),
    ]
