# Generated by Django 3.2.4 on 2022-01-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20220130_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_translate',
            name='catalog',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Смотреть каталог'),
        ),
        migrations.AlterField(
            model_name='index_translate',
            name='catalog_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Смотреть каталог'),
        ),
        migrations.AlterField(
            model_name='index_translate',
            name='catalog_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Смотреть каталог'),
        ),
        migrations.AlterField(
            model_name='index_translate',
            name='catalog_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Смотреть каталог'),
        ),
    ]
