# Generated by Django 3.2.4 on 2022-01-31 06:56

import django.core.validators
from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_alter_index_main_model_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_main',
            name='model_file',
            field=models.FileField(blank=True, help_text='Формат файла: zip. Ограничение размера: 1 Мбайт.', upload_to=index.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['zip'])], verbose_name='Файл модели'),
        ),
    ]
