# Generated by Django 3.2.4 on 2022-01-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advice_blocks',
            options={'ordering': ['order'], 'verbose_name': 'Блоки страницы советов', 'verbose_name_plural': 'Блоки страницы советов'},
        ),
        migrations.AlterModelOptions(
            name='advice_page',
            options={'ordering': ['order'], 'verbose_name': 'Страница советов по сборке', 'verbose_name_plural': 'Страница советов по сборке'},
        ),
        migrations.AddField(
            model_name='advice_blocks',
            name='order',
            field=models.IntegerField(null=True, verbose_name='Порядок показа'),
        ),
        migrations.AlterField(
            model_name='advice_page',
            name='order',
            field=models.IntegerField(null=True, verbose_name='Порядок показа'),
        ),
    ]
