# Generated by Django 3.2.4 on 2022-01-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0003_auto_20220119_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice_blocks',
            name='title_paragraph1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый заголовок пункта списка'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='title_paragraph1_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый заголовок пункта списка'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='title_paragraph1_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый заголовок пункта списка'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='title_paragraph1_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый заголовок пункта списка'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='title_paragraph2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Второй заголовок пункта списка'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='title_paragraph2_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Второй заголовок пункта списка'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='title_paragraph2_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Второй заголовок пункта списка'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='title_paragraph2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Второй заголовок пункта списка'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='title_paragraph3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Третий заголовок пункта списка'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='title_paragraph3_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Третий заголовок пункта списка'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='title_paragraph3_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Третий заголовок пункта списка'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='title_paragraph3_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Третий заголовок пункта списка'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='title_paragraph4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Четвертый заголовок пункта списка'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='title_paragraph4_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Четвертый заголовок пункта списка'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='title_paragraph4_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Четвертый заголовок пункта списка'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='title_paragraph4_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Четвертый заголовок пункта списка'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='title_paragraph5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пятый заголовок пункта списка'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='title_paragraph5_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пятый заголовок пункта списка'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='title_paragraph5_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пятый заголовок пункта списка'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='title_paragraph5_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пятый заголовок пункта списка'),
        ),
    ]
