# Generated by Django 3.2.4 on 2022-01-19 11:56

import advice.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0004_auto_20220119_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advice_page',
            options={'ordering': ['order'], 'verbose_name': 'Список советов', 'verbose_name_plural': 'Список советов'},
        ),
        migrations.AddField(
            model_name='advice_page',
            name='is_active_en',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AddField(
            model_name='advice_page',
            name='is_active_fr',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AddField(
            model_name='advice_page',
            name='is_active_ru',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=advice.models.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='slide_picture_1',
            field=models.ImageField(blank=True, null=True, upload_to=advice.models.get_file_path, verbose_name='Первое изображение слайдера'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='slide_picture_2',
            field=models.ImageField(blank=True, null=True, upload_to=advice.models.get_file_path, verbose_name='Второе изображение слайдера'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='slide_picture_3',
            field=models.ImageField(blank=True, null=True, upload_to=advice.models.get_file_path, verbose_name='Третье изображение слайдера'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='slide_picture_4',
            field=models.ImageField(blank=True, null=True, upload_to=advice.models.get_file_path, verbose_name='Четвертое изображение слайдера'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='slide_picture_5',
            field=models.ImageField(blank=True, null=True, upload_to=advice.models.get_file_path, verbose_name='Пятое изображение слайдера'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='slide_picture_6',
            field=models.ImageField(blank=True, null=True, upload_to=advice.models.get_file_path, verbose_name='Шестое изображение слайдера'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='slide_picture_7',
            field=models.ImageField(blank=True, null=True, upload_to=advice.models.get_file_path, verbose_name='Седьмое изображение слайдера'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='slide_picture_8',
            field=models.ImageField(blank=True, null=True, upload_to=advice.models.get_file_path, verbose_name='Восьмое изображение слайдера'),
        ),
        migrations.AlterField(
            model_name='advice_page',
            name='intro_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Вступительный текст'),
        ),
        migrations.AlterField(
            model_name='advice_page',
            name='intro_text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Вступительный текст'),
        ),
        migrations.AlterField(
            model_name='advice_page',
            name='intro_text_fr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Вступительный текст'),
        ),
        migrations.AlterField(
            model_name='advice_page',
            name='intro_text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Вступительный текст'),
        ),
    ]
