# Generated by Django 3.2.4 on 2022-01-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0008_auto_20220119_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice_main',
            name='advice',
            field=models.CharField(blank=True, max_length=255, verbose_name='Советы по сборке'),
        ),
        migrations.AlterField(
            model_name='advice_main',
            name='advice_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Советы по сборке'),
        ),
        migrations.AlterField(
            model_name='advice_main',
            name='advice_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Советы по сборке'),
        ),
        migrations.AlterField(
            model_name='advice_main',
            name='advice_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Советы по сборке'),
        ),
    ]
