# Generated by Django 3.2.4 on 2022-01-20 06:13

import advice.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0009_auto_20220120_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice_page',
            name='main_photo_xxl2x',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, null=True, quality=80, size=[1600, 1200], upload_to=advice.models.get_file_path, verbose_name='Основное изображение'),
        ),
    ]
