# Generated by Django 3.2.4 on 2022-01-20 06:24

import advice.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0010_alter_advice_page_main_photo_xxl2x'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advice_blocks',
            old_name='image_xs',
            new_name='slide_picture_1_original',
        ),
        migrations.RenameField(
            model_name='advice_blocks',
            old_name='image_xs2x',
            new_name='slide_picture_1_xs',
        ),
        migrations.RenameField(
            model_name='advice_blocks',
            old_name='image_xxl',
            new_name='slide_picture_1_xs2x',
        ),
        migrations.RenameField(
            model_name='advice_blocks',
            old_name='image_xxl2x',
            new_name='slide_picture_1_xxl',
        ),
        migrations.RemoveField(
            model_name='advice_blocks',
            name='slide_picture_1',
        ),
        migrations.RemoveField(
            model_name='advice_blocks',
            name='slide_picture_2',
        ),
        migrations.RemoveField(
            model_name='advice_blocks',
            name='slide_picture_3',
        ),
        migrations.RemoveField(
            model_name='advice_blocks',
            name='slide_picture_4',
        ),
        migrations.RemoveField(
            model_name='advice_blocks',
            name='slide_picture_5',
        ),
        migrations.RemoveField(
            model_name='advice_blocks',
            name='slide_picture_6',
        ),
        migrations.RemoveField(
            model_name='advice_blocks',
            name='slide_picture_7',
        ),
        migrations.RemoveField(
            model_name='advice_blocks',
            name='slide_picture_8',
        ),
        migrations.AddField(
            model_name='advice_blocks',
            name='slide_picture_1_xxl2x',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, null=True, quality=80, size=[2400, 1800], upload_to=advice.models.get_file_path, verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='advice_blocks',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, null=True, quality=80, size=[1600, 1200], upload_to=advice.models.get_file_path, verbose_name='Основное изображение'),
        ),
    ]
