# Generated by Django 3.2.4 on 2022-01-20 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0012_auto_20220120_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advice_blocks',
            name='description',
        ),
        migrations.RemoveField(
            model_name='advice_blocks',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='advice_blocks',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='advice_blocks',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='advice_blocks',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='advice_blocks',
            name='keywords_en',
        ),
        migrations.RemoveField(
            model_name='advice_blocks',
            name='keywords_fr',
        ),
        migrations.RemoveField(
            model_name='advice_blocks',
            name='keywords_ru',
        ),
        migrations.RemoveField(
            model_name='advice_blocks',
            name='title',
        ),
        migrations.RemoveField(
            model_name='advice_blocks',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='advice_blocks',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='advice_blocks',
            name='title_ru',
        ),
    ]
