# Generated by Django 3.2.4 on 2022-01-20 12:04

import advice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0016_auto_20220120_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice_blocks',
            name='slide_picture_1_thumb_xs',
            field=models.ImageField(blank=True, null=True, upload_to=advice.models.get_file_path),
        ),
        migrations.AddField(
            model_name='advice_blocks',
            name='slide_picture_1_thumb_xs2x',
            field=models.ImageField(blank=True, null=True, upload_to=advice.models.get_file_path),
        ),
    ]
